### ISSUE TITLE
Stocks Tracking

### ISSUE THREAD

**Issue by gigabyteservice** [saleem-hadad/finance#2]
Think about managing your stock market portfolio or e.g on date: 18/01/2022 I have bought Xyz stock at $100 at 100 quantity and sold at 50 stock at $120 and another 50 stocks are sold at $90 so total I have earned/lost  XX  much by this month etc and then profit and lost take it as income and expense.

**Comment by saleem-hadad** [comment]
Right now, I don't have any plan for integrating stock investment in this app but feel free to extend it according to your need.
