### ISSUE TITLE
ERROR [ 4/11] RUN apt-get update     && apt-get install -y gnupg gosu curl ca-certificates zip unzip git supervisor sqlite3 libcap2-bin libpng-dev python2     && mkdir -p ~/.gnupg     && chmod   0.7s

### ISSUE THREAD

**Issue by EnricoPezzano** [saleem-hadad/finance#44]
![Schermata 2023-04-24 alle 18 15 20](https://user-images.githubusercontent.com/53240167/234056164-37fc2ac0-d199-466f-90f1-85442e15daaf.jpg)

**Comment by saleem-hadad** [comment]
please use the updated docker image installation. The old one is buggy. Check the README
